### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-openfoam#36]

**Comment by nathanfranklin** [comment]
@jmarcelogimenez , @khiltunen ,  a LICENSE file should be added.  It sounded like GPL was the required license for simphony-openfoam

**Comment by santiagomarquezd** [comment]
Hi @nathanfranklin, @khiltunen and @jmarcelogimenez FOAM's derivative work have their own license header in each file. Maybe another file should be added for the original contributed coded. I agree that GPL license is the correct one, however the description should be update in the document since there simphony-openfoam appears as being LGPL licensed work.

**Comment by jmarcelogimenez** [comment]
We added the LICENSE file with the corresponding GPL license in the branch fix-issues-july2015.
Although the recommended practice is to add the license notice in every file, only specifying the license of the entire project in a license file (LICESE or COPYING) in the root folder is enough.

**Comment by nathanfranklin** [comment]
LICENSE file is still missing.

**Comment by khiltunen** [comment]
LICENSE file will be added to branch use-common-0.2

**Comment by nathanfranklin** [comment]
> LICENSE file will be added to branch use-common-0.2 

There is also PR #50

**Comment by nathanfranklin** [comment]
closed by #50
