### ISSUE TITLE
Internal wrapper: Modifications of input values in poiseuille example not considered in simulation run

### ISSUE THREAD

**Issue by TobiasRasp** [simphony/simphony-openfoam#57]
Using the internal wrapper, interactive parameter settings e.g. via wrapper.SP[CUBA.NUMBER_OF_TIME_STEPS] or via wrapper.SP[CUBA.DYNAMIC_VISCOSITY] in the poiseuille example are not reflected in the respective run files controlDict and transportProperties.
Instead some static values seem to be used independent of what is given in the example.

For the IO control wrapper everything works fine!

**Comment by khiltunen** [comment]
@jmarcelogimenez can you look at this. I made a quick test and add the following printing sentences to the end of the  interface function modifyNumerics

Foam::Info<< "controlDict.endTime " << controlDict.lookup("endTime") <<Foam::endl;
Foam::Info<< "runTimes[name].endTime " << (*(runTimes[name])).endTime() <<Foam::endl;
Foam::Info<< "runTimes[name].controlDict().lookup(endTime) " << (*(runTimes[name])).controlDict().lookup("endTime") <<Foam::endl;

which gives

controlDict.endTime 1(1000)
runTimes[name].endTime endTime [0 0 1 0 0 0 0] 1
runTimes[name].controlDict().lookup(endTime) 1(1000)

I suppose that the solver gets now value 1 instead of 1000 for the endTime

**Comment by jmarcelogimenez** [comment]
Bug solved in branch #issue57

**Comment by khiltunen** [comment]
@jmarcelogimenez. I tested and seems to work now.

**Comment by jmarcelogimenez** [comment]
Ok, If there is not any objection, I'll merge

**Comment by TobiasRasp** [comment]
Time control handling works fine now! 
But as far as I see, the values of CUBA.DENSITY and CUBA.DYNAMIC_VISCOSITY that can be set e.g. in the poiseuille example are not handed over to the OpenFoam solver. Instead, the default value for nu from the template in foam_internalwrapper/foam_dicts.py (line 42) is used, which is zero. Please correct me from wrong, if this is not true, but I couldn't find a viscosity treatment in the internal wrapper code.

**Comment by jmarcelogimenez** [comment]
Currently is a pending task for internal interface. But it will be developed directly over the branch migration_OF24.

**Comment by khiltunen** [comment]
Fixed in version 0.2.0
